import type { WalkthroughScript } from "../WalkthroughTypes";

const MacroCalculatorScript: WalkthroughScript = {
  id: "macro-calculator-walkthrough",
  featureId: "MACRO_CALCULATOR",
  title: "Macro Calculator",
  uiReady: true,
  steps: [
    {
      id: "intro",
      targetTestId: "macro-goal-selector",
      description: "Welcome to the Macro Calculator! This tool sets your daily nutrition targets based on your goals and body stats. Let's start by choosing your primary goal.",
      message: "Welcome to the Macro Calculator! This sets your daily nutrition targets. Let's start by choosing your goal.",
      speak: "Welcome to the Macro Calculator. Let's set your nutrition targets.",
      spotlight: true,
    },
    {
      id: "goal",
      targetTestId: "macro-goal-selector",
      description: "Choose your primary goal: Fat Loss, Maintenance, or Muscle Gain. This determines your calorie target.",
      message: "Choose your goal: Fat Loss, Maintenance, or Muscle Gain.",
      speak: "Choose your goal.",
      spotlight: true,
    },
    {
      id: "body-type",
      targetTestId: "macro-body-type-selector",
      description: "Select your body type. This fine-tunes your carb and fat distribution for your metabolism.",
      message: "Select your body type: Ectomorph, Mesomorph, or Endomorph.",
      speak: "Select your body type.",
      spotlight: true,
    },
    {
      id: "stats",
      targetTestId: "macro-details-card",
      description: "Enter your body stats: age, height, weight, and biological sex. These calculate your baseline calorie needs.",
      message: "Fill in your age, height, weight, and sex.",
      speak: "Enter your body stats.",
      spotlight: true,
    },
    {
      id: "activity",
      targetTestId: "macro-activity-selector",
      description: "Select your typical activity level. This adjusts your calorie needs based on how active you are most days.",
      message: "Choose your activity level: Sedentary, Light, Moderate, Very Active, or Extra.",
      speak: "Select your activity level.",
      spotlight: true,
    },
    {
      id: "sync-weight",
      targetTestId: "macro-sync-weight-button",
      description: "Optional: Sync your current weight to My Biometrics for tracking progress over time.",
      message: "Tap Sync Weight to save your weight to biometrics tracking.",
      speak: "Sync your weight if you want to track progress.",
      spotlight: true,
    },
    {
      id: "results",
      targetTestId: "macro-targets-card",
      description: "Here are your personalized macro targets! Review your daily calories, protein, carbs, and fats.",
      message: "Review your personalized daily macro targets.",
      speak: "Here are your targets.",
      spotlight: true,
      waitForEvent: { testId: "macro-results-ready", event: "ready" },
    },
    {
      id: "save",
      targetTestId: "macro-save-button",
      description: "Tap 'Set Macro Targets' to save these as your daily nutrition goals. This will apply them across the app.",
      message: "Tap 'Set Macro Targets' to save and apply these to your profile.",
      speak: "Save your targets to use them app-wide.",
      spotlight: true,
      waitForEvent: { testId: "macro-targets-saved", event: "done" },
    },
    {
      id: "complete",
      targetTestId: "macro-save-button",
      description: "Perfect! Your macro targets are set. You'll be taken to My Biometrics to start tracking your progress.",
      message: "Targets saved! Heading to My Biometrics for progress tracking.",
      speak: "Targets saved! You'll track progress in Biometrics.",
      spotlight: false,
    },
  ],
};

export default MacroCalculatorScript;
