import type { WalkthroughScript } from "../WalkthroughTypes";

const WeeklyMealBuilderScript: WalkthroughScript = {
  id: "weekly-meal-builder",
  featureId: "WEEKLY_MEAL_BUILDER",
  title: "Weekly Meal Builder",
  uiReady: true, // ✅ ACTIVATED: All 17 data-testid anchors + 4 custom events wired (Phase C.2 complete Nov 24 2025)
  steps: [
    {
      id: "intro",
      targetTestId: "weekly-builder-header",
      description: "Welcome to the Weekly Meal Builder. Let's create your first day. We'll begin with breakfast.",
      message: "Welcome to the Weekly Meal Builder. Let's create your first day. We'll begin with breakfast.",
      speak: "Welcome to the Weekly Meal Builder. Let's create your first day.",
      spotlight: true,
    },
    {
      id: "breakfast",
      targetTestId: "meal-slot-breakfast",
      description: "Tap breakfast to create your first meal. You can build it manually or use AI to generate it.",
      message: "Tap breakfast to create your first meal. You can build it manually or use AI to generate it.",
      speak: "Tap breakfast to create your first meal.",
      spotlight: true,
      waitForEvent: { testId: "meal-filled-breakfast", event: "filled" },
    },
    {
      id: "lunch",
      targetTestId: "meal-slot-lunch",
      description: "Now tap lunch and build your next meal.",
      message: "Now tap lunch and build your next meal.",
      speak: "Now tap lunch and build your next meal.",
      spotlight: true,
      waitForEvent: { testId: "meal-filled-lunch", event: "filled" },
    },
    {
      id: "dinner",
      targetTestId: "meal-slot-dinner",
      description: "Next is dinner. Choose or generate a meal.",
      message: "Next is dinner. Choose or generate a meal.",
      speak: "Next is dinner.",
      spotlight: true,
      waitForEvent: { testId: "meal-filled-dinner", event: "filled" },
    },
    {
      id: "snack",
      targetTestId: "meal-slot-snack",
      description: "Now add your snack. This completes your day's meals.",
      message: "Now add your snack. This completes your day's meals.",
      speak: "Now add your snack.",
      spotlight: true,
      waitForEvent: { testId: "meal-filled-snack", event: "filled" },
    },
    {
      id: "totals",
      targetTestId: "daily-totals-card",
      description: "Great! Here's your combined daily totals. Once the day is complete, you're ready to duplicate it.",
      message: "Great! Here's your combined daily totals. Once the day is complete, you're ready to duplicate it.",
      speak: "Great! Here's your combined daily totals.",
      spotlight: true,
      waitForEvent: { testId: "daily-totals-ready", event: "ready" },
    },
    {
      id: "duplicate-menu",
      targetTestId: "duplicate-button",
      description: "Tap 'Duplicate' to copy this day across the week.",
      message: "Tap 'Duplicate' to copy this day across the week.",
      speak: "Tap Duplicate to copy this day across the week.",
      spotlight: true,
    },
    {
      id: "duplicate-days",
      targetTestId: "duplicate-days-panel",
      description: "Choose the days you want to copy your meals to: Monday through Sunday, any combination.",
      message: "Choose the days you want to copy your meals to: Monday through Sunday, any combination.",
      speak: "Choose the days you want to copy your meals to.",
      spotlight: true,
      waitForEvent: { testId: "duplicate-days-selected", event: "chosen" },
    },
    {
      id: "confirm-duplicate",
      targetTestId: "duplicate-confirm-button",
      description: "Tap 'Duplicate' to finish the process. Your week is now built.",
      message: "Tap 'Duplicate' to finish the process. Your week is now built.",
      speak: "Tap Duplicate to finish the process.",
      spotlight: true,
    },
    {
      id: "shopping",
      targetTestId: "send-week-to-shopping",
      description: "Finally, you can send your entire week to the shopping list. Most users shop weekly, not daily.",
      message: "Finally, you can send your entire week to the shopping list. Most users shop weekly, not daily.",
      speak: "Finally, you can send your entire week to the shopping list.",
      spotlight: true,
      waitForEvent: { testId: "shopping-week-sent", event: "done" },
    },
    {
      id: "done",
      targetTestId: "weekly-builder-header",
      description: "Your weekly plan is complete! You're all set.",
      message: "Your weekly plan is complete! You're all set.",
      speak: "Your weekly plan is complete!",
      spotlight: false,
      end: true,
    },
  ],
};

export default WeeklyMealBuilderScript;
