import { defineConfig } from "drizzle-kit";

export default defineConfig({
  out: "./migrations",
  schema: [
    "./shared/schema.ts",
    "./server/db/schema/bodyComposition.ts",
    "./server/db/schema/organizations.ts",
    "./server/db/schema/userBehaviorSummary.ts",
    "./server/db/schema/companionProfiles.ts",
    "./server/db/schema/clinicalLabs.ts",
    "./server/db/schema/clinicalProtocolRecommendations.ts",
    "./server/db/schema/aiUsage.ts",
    "./server/db/schema/auditLog.ts",
    "./server/db/schema/builderPlans.ts",
    "./server/db/schema/careTeam.ts",
    "./server/db/schema/chefSignatureImports.ts",
    "./server/db/schema/chefSignatureLibrary.ts",
    "./server/db/schema/creatorMeals.ts",
    "./server/db/schema/creatorOnboardingSubmissions.ts",
    "./server/db/schema/creators.ts",
    "./server/db/schema/creatorSystemConfigs.ts",
    "./server/db/schema/certifications.ts",
    "./server/db/schema/founders.ts",
    "./server/db/schema/generatedMeals.ts",
    "./server/db/schema/glp1Shots.ts",
    "./server/db/schema/householdProfiles.ts",
    "./server/db/schema/legal.ts",
    "./server/db/schema/mealBoards.ts",
    "./server/db/schema/mealImageCache.ts",
    "./server/db/schema/mealLibrary.ts",
    "./server/db/schema/mindset.ts",
    "./server/db/schema/mybestlife.ts",
    "./server/db/schema/patientAssignment.ts",
    "./server/db/schema/procare.ts",
    "./server/db/schema/restaurantGuideSessions.ts",
    "./server/db/schema/savedMeals.ts",
    "./server/db/schema/sms.ts",
    "./server/db/schema/studio.ts",
    "./server/db/schema/trivia.ts",
  ],
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
