export const nutritionDisclaimer = {
  title: "Nutrition Information Disclaimer",
  version: 1,
  content: `
My Perfect Meals provides nutrition guidance and meal planning tools designed to support healthy lifestyle choices.

The platform does not provide medical advice, diagnosis, or treatment.

Any nutrition recommendations generated by the app or provided by coaches are intended for educational purposes only.

Individuals with medical conditions should consult a licensed healthcare provider before making dietary changes.
`,
};
