import { pgTable, text, date, numeric, jsonb, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Monthly behavioral intelligence summaries.
 *
 * Generated by the data retention cron BEFORE old meal_logs_enhanced rows
 * are purged. Each row represents one user's entire behavior for one calendar
 * month, compressed from potentially hundreds of raw log rows into a single
 * intelligence record.
 *
 * Design principles:
 *   - Retain meaning, discard raw noise
 *   - Nullable fields are intentional: populated as more data sources come online
 *     (cuisine tagging, DB-backed scan grades, macro target tracking)
 *   - Upsert-safe: ON CONFLICT updates so re-runs are idempotent
 *
 * Future uses:
 *   - "Your Nutrition Journey" storytelling surface
 *   - Physician / coach adherence dashboards
 *   - AI coaching pattern detection ("you struggle on weekends")
 *   - Adaptive meal generation (lean into what works)
 */
export const userBehaviorMonthlySummary = pgTable(
  "user_behavior_monthly_summary",
  {
    id: text("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),

    userId: text("user_id").notNull(),

    /** First day of the calendar month, e.g. "2025-03-01" */
    month: date("month").notNull(),

    /** Average daily macros across all logged meals in the month */
    avgProtein:  numeric("avg_protein"),
    avgCarbs:    numeric("avg_carbs"),
    avgFat:      numeric("avg_fat"),
    avgCalories: numeric("avg_calories"),

    /**
     * % of days in the month where the user had at least one meal log.
     * Simple but powerful adherence signal.
     */
    mealConsistencyScore: numeric("meal_consistency_score"),
    adherencePercentage:  numeric("adherence_percentage"),

    /**
     * Distribution of meal slots: { breakfast: N, lunch: N, dinner: N, snack: N }
     * Reveals eating pattern structure (skippers, snackers, dinner-heavy, etc.)
     */
    topMealTypes: jsonb("top_meal_types"),

    /**
     * Distribution of log sources: { generated: N, barcode: N, manual: N }
     * Tracks platform engagement and meal discovery method over time.
     */
    topDietPatterns: jsonb("top_diet_patterns"),

    /**
     * NULL until macro targets are tracked per-user over time.
     * Will become: actual_avg / target_avg * 100 per macro
     */
    macroComplianceScore: numeric("macro_compliance_score"),

    /**
     * NULL until cuisine tagging is added to meal generation.
     * Will become: most frequent cuisine tag across generated meals.
     */
    mostCommonCuisine: text("most_common_cuisine"),

    /**
     * NULL until Smart Scan grades are persisted to the database.
     * Currently stored in localStorage only.
     */
    scanGradeAverage: text("scan_grade_average"),
    scanFrequency:    numeric("scan_frequency"),

    summarizedAt: timestamp("summarized_at", { withTimezone: true }).defaultNow(),
  },
  (t) => ({
    userMonthUniq: uniqueIndex("ubms_user_month_uniq").on(t.userId, t.month),
  })
);
