// server/config/stripeProducts.ts

export const STRIPE_PRODUCTS = {
  mpm_basic_monthly: {
    sku: "mpm_basic_monthly",
    tier: "basic",
    group: "consumer",
    seats: 1,
    deliverable: false,
    proCollab: false,
    familyPlan: false,
  },
  mpm_premium_monthly: {
    sku: "mpm_premium_monthly",
    tier: "premium",
    group: "consumer",
    seats: 1,
    deliverable: false,
    proCollab: false,
    familyPlan: false,
  },
  mpm_premium_beta_monthly: {
    sku: "mpm_premium_beta_monthly",
    tier: "premium",
    group: "consumer",
    seats: 1,
    hidden: true,
    deliverable: false,
    proCollab: false,
    familyPlan: false,
  },
  mpm_ultimate_monthly: {
    sku: "mpm_ultimate_monthly",
    tier: "ultimate",
    group: "consumer",
    seats: 1,
    deliverable: true,
    proCollab: true,
    familyPlan: false,
  },
  mpm_family_base_monthly: {
    sku: "mpm_family_base_monthly",
    tier: "premium",
    group: "family",
    seats: 4,
    deliverable: false,
    proCollab: false,
    familyPlan: true,
  },
  mpm_family_all_premium_monthly: {
    sku: "mpm_family_all_premium_monthly",
    tier: "premium",
    group: "family",
    seats: 4,
    deliverable: false,
    proCollab: false,
    familyPlan: true,
  },
  mpm_family_all_ultimate_monthly: {
    sku: "mpm_family_all_ultimate_monthly",
    tier: "ultimate",
    group: "family",
    seats: 4,
    deliverable: true,
    proCollab: true,
    familyPlan: true,
  },
  mpm_procare_monthly: {
    sku: "mpm_procare_monthly",
    tier: "ultimate",
    group: "pro",
    seats: 1,
    proPlan: true,
    deliverable: false,
  },
} as const;
