// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chef-kitchens/KitchenLanding.tsx": () => import("../components/mockups/chef-kitchens/KitchenLanding.tsx"),
  "./components/mockups/chef-kitchens/LifestylePage.tsx": () => import("../components/mockups/chef-kitchens/LifestylePage.tsx"),
  "./components/mockups/chef-kitchens/OnboardingPacket.tsx": () => import("../components/mockups/chef-kitchens/OnboardingPacket.tsx"),
  "./components/mockups/chef-kitchens/RushKitchenLanding.tsx": () => import("../components/mockups/chef-kitchens/RushKitchenLanding.tsx")
};
