#!/bin/bash
# ============================================================================
#  Modal + Sheet/Drawer Viewport Gate — Test Runner  (Gate 1)
#
#  Runs the Playwright responsive viewport tests for shared dialog primitives
#  and sheet/drawer primitives, and on success writes fingerprints so
#  pre-publish-validate.sh can confirm the tests passed against the current
#  file state.
#
#  Usage:
#    bash scripts/run-modal-viewport-tests.sh
#
#  After a successful run:
#    • pre-publish-validate.sh section 7a PASSES as long as universal-modal.tsx
#      and dialog.tsx have not changed since this run.
#    • pre-publish-validate.sh section 7b PASSES as long as sheet.tsx and
#      drawer.tsx have not changed since this run.
#
#  Architecture reference: docs/responsive-ui-regression-guard.md Gate 1
# ============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

# ── Modal specs + primitives ──────────────────────────────────────────────────
SPEC_A="client/e2e/inspiration-capture-modal-viewport.spec.ts"
SPEC_B="client/e2e/universal-modal-viewport.spec.ts"
MODAL_LOCK="scripts/checksums/modal-viewport-gate.lock"
PRIMITIVE_A="client/src/components/ui/universal-modal.tsx"
PRIMITIVE_B="client/src/components/ui/dialog.tsx"

# ── Sheet/Drawer spec + primitives ───────────────────────────────────────────
SPEC_C="client/e2e/bottom-sheet-viewport.spec.ts"
SHEET_LOCK="scripts/checksums/sheet-viewport-gate.lock"
PRIMITIVE_C="client/src/components/ui/sheet.tsx"
PRIMITIVE_D="client/src/components/ui/drawer.tsx"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Modal + Sheet/Drawer Viewport Gate — Runner (Gate 1)   ║"
echo "║   docs/responsive-ui-regression-guard.md                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Pre-flight: verify watched files exist ────────────────────────────────────

MISSING=0
for f in "$SPEC_A" "$SPEC_B" "$SPEC_C"; do
  if [ ! -f "$f" ]; then
    echo -e "${RED}❌ Spec not found: $f${NC}"
    MISSING=1
  fi
done
for f in "$PRIMITIVE_A" "$PRIMITIVE_B" "$PRIMITIVE_C" "$PRIMITIVE_D"; do
  if [ ! -f "$f" ]; then
    echo -e "${RED}❌ Watched primitive not found: $f${NC}"
    MISSING=1
  fi
done
if [ "$MISSING" -eq 1 ]; then
  echo "   Update the SPEC_* / PRIMITIVE_* variables in this script"
  echo "   if any files were moved or renamed."
  exit 1
fi

# ── Run all Playwright viewport suites ───────────────────────────────────────

echo -e "${CYAN}Running Playwright specs:${NC}"
echo "  $SPEC_A"
echo "  $SPEC_B"
echo "  $SPEC_C"
echo ""

if npx playwright test "$SPEC_A" "$SPEC_B" "$SPEC_C"; then

  echo ""
  echo -e "${GREEN}✅ All viewport tests passed.${NC}"

  # Compute SHA-256 fingerprints of the watched primitives
  SHA_A=$(sha256sum "$PRIMITIVE_A" | awk '{print $1}')
  SHA_B=$(sha256sum "$PRIMITIVE_B" | awk '{print $1}')
  SHA_C=$(sha256sum "$PRIMITIVE_C" | awk '{print $1}')
  SHA_D=$(sha256sum "$PRIMITIVE_D" | awk '{print $1}')
  TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$(dirname "$MODAL_LOCK")"

  # ── Write modal lock ──────────────────────────────────────────────────────
  cat > "$MODAL_LOCK" <<EOF
# Modal Viewport Gate — fingerprint of last passing run
# Generated by: scripts/run-modal-viewport-tests.sh
# Specs: $SPEC_A
#        $SPEC_B
# Architecture: docs/responsive-ui-regression-guard.md Gate 1
#
# pre-publish-validate.sh section 7a reads this file.
timestamp=$TS
universal_modal_sha256=$SHA_A
dialog_sha256=$SHA_B
EOF

  # ── Write sheet/drawer lock ───────────────────────────────────────────────
  cat > "$SHEET_LOCK" <<EOF
# Sheet/Drawer Viewport Gate — fingerprint of last passing run
# Generated by: scripts/run-modal-viewport-tests.sh
# Spec: $SPEC_C
# Architecture: docs/responsive-ui-regression-guard.md Gate 1
#
# pre-publish-validate.sh section 7b reads this file.
timestamp=$TS
sheet_sha256=$SHA_C
drawer_sha256=$SHA_D
EOF

  echo ""
  echo -e "${GREEN}Fingerprints written:${NC}"
  echo "  Modal lock:  $MODAL_LOCK"
  echo "    universal-modal.tsx:  $SHA_A"
  echo "    dialog.tsx:          $SHA_B"
  echo ""
  echo "  Sheet lock:  $SHEET_LOCK"
  echo "    sheet.tsx:   $SHA_C"
  echo "    drawer.tsx:  $SHA_D"
  echo ""
  echo "  timestamp: $TS"
  echo ""
  echo -e "${CYAN}You can now run:${NC} bash scripts/pre-publish-validate.sh"
  echo ""

else
  echo ""
  echo -e "${RED}❌ Viewport tests FAILED — fingerprints NOT updated.${NC}"
  echo "   Fix the failures before publishing."
  echo "   View the HTML report:  npx playwright show-report"
  echo ""
  exit 1
fi
