#!/bin/bash
# ============================================================================
#  Modal Viewport Gate — Test Runner  (Gate 1)
#
#  Runs the Playwright responsive viewport tests for shared dialog primitives,
#  and on success writes a fingerprint so pre-publish-validate.sh can confirm
#  the tests passed against the current file state.
#
#  Usage:
#    bash scripts/run-modal-viewport-tests.sh
#
#  After a successful run, pre-publish-validate.sh section 7a will PASS as
#  long as universal-modal.tsx and dialog.tsx have not changed since this run.
#
#  Architecture reference: docs/responsive-ui-regression-guard.md Gate 1
# ============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

SPEC="client/e2e/universal-modal-viewport.spec.ts"
LOCK_FILE="scripts/checksums/modal-viewport-gate.lock"
PRIMITIVE_A="client/src/components/ui/universal-modal.tsx"
PRIMITIVE_B="client/src/components/ui/dialog.tsx"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Modal Viewport Gate — Responsive Layout Test Runner    ║"
echo "║   Gate 1 — docs/responsive-ui-regression-guard.md        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Pre-flight: verify watched files exist ────────────────────────────────────

if [ ! -f "$SPEC" ]; then
  echo -e "${RED}❌ Spec not found: $SPEC${NC}"
  echo "   Create the spec or update SPEC in this script."
  exit 1
fi

MISSING_PRIMITIVE=0
for f in "$PRIMITIVE_A" "$PRIMITIVE_B"; do
  if [ ! -f "$f" ]; then
    echo -e "${RED}❌ Watched primitive not found: $f${NC}"
    MISSING_PRIMITIVE=1
  fi
done
if [ "$MISSING_PRIMITIVE" -eq 1 ]; then
  echo "   Update the PRIMITIVE_A / PRIMITIVE_B variables in this script if the"
  echo "   files were moved or renamed."
  exit 1
fi

# ── Run the Playwright suite ──────────────────────────────────────────────────

echo -e "${CYAN}Running Playwright spec:${NC} $SPEC"
echo ""

if npx playwright test "$SPEC"; then

  echo ""
  echo -e "${GREEN}✅ All modal viewport tests passed.${NC}"

  # Compute SHA-256 fingerprints of the watched primitives
  SHA_A=$(sha256sum "$PRIMITIVE_A" | awk '{print $1}')
  SHA_B=$(sha256sum "$PRIMITIVE_B" | awk '{print $1}')
  TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$(dirname "$LOCK_FILE")"
  cat > "$LOCK_FILE" <<EOF
# Modal Viewport Gate — fingerprint of last passing run
# Generated by: scripts/run-modal-viewport-tests.sh
# Spec:         $SPEC
# Architecture: docs/responsive-ui-regression-guard.md Gate 1
#
# pre-publish-validate.sh reads this file.  If universal-modal.tsx or
# dialog.tsx changes after this run, the fingerprints will not match and
# publish will be blocked until tests are re-run.
#
# To re-activate the gate after editing a shared primitive:
#   bash scripts/run-modal-viewport-tests.sh
timestamp=$TS
universal_modal_sha256=$SHA_A
dialog_sha256=$SHA_B
EOF

  echo ""
  echo -e "${GREEN}Fingerprint written to $LOCK_FILE${NC}"
  echo "  timestamp:            $TS"
  echo "  universal-modal.tsx:  $SHA_A"
  echo "  dialog.tsx:           $SHA_B"
  echo ""
  echo -e "${CYAN}You can now run:${NC} bash scripts/pre-publish-validate.sh"
  echo ""

else
  echo ""
  echo -e "${RED}❌ Modal viewport tests FAILED — fingerprint NOT updated.${NC}"
  echo "   Fix the failures before publishing."
  echo "   View the HTML report:  npx playwright show-report"
  echo ""
  exit 1
fi
