import { db } from "../db";
import { mealLibraryItems } from "../../shared/schema";

type StudioType = "craving" | "fridge" | "dessert";

interface SeedMeal {
  title: string;
  description: string;
  studio: StudioType;
  mealType: string;
  cuisine?: string;
  ingredients: Array<{ name: string; quantity?: string; amount?: number; unit?: string; notes?: string }>;
  steps: string[];
  macros: { calories: number; protein: number; carbs: number; fat: number; fiber?: number };
  allergenFlags: Record<string, boolean>;
  dietFlags: Record<string, boolean>;
  cravingTags: Record<string, number>;
  emotionTags: Record<string, number>;
  qualityScore: number;
  servings: number;
  prepMinutes?: number;
  cookMinutes?: number;
}

const CRAVING_MEALS: SeedMeal[] = [
  {
    title: "High-Protein Turkey Taco Bowl",
    description: "Satisfying ground turkey with Mexican spices, served over cauliflower rice with fresh toppings",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Mexican",
    ingredients: [
      { name: "ground turkey", amount: 200, unit: "g", notes: "93% lean" },
      { name: "cauliflower rice", amount: 150, unit: "g" },
      { name: "black beans", amount: 80, unit: "g", notes: "drained" },
      { name: "cherry tomatoes", amount: 100, unit: "g", notes: "halved" },
      { name: "avocado", amount: 50, unit: "g", notes: "diced" },
      { name: "lime", amount: 1, unit: "wedge" },
      { name: "taco seasoning", amount: 1, unit: "tbsp" },
    ],
    steps: [
      "Brown ground turkey in a skillet over medium-high heat for 5-6 minutes.",
      "Add taco seasoning and 2 tablespoons water, stir to coat.",
      "Microwave cauliflower rice according to package directions.",
      "Build bowl: cauliflower rice base, seasoned turkey, black beans.",
      "Top with cherry tomatoes, avocado, and a squeeze of lime.",
    ],
    macros: { calories: 420, protein: 38, carbs: 28, fat: 18, fiber: 9 },
    allergenFlags: {},
    dietFlags: { glp1: true, diabetes: true, highProtein: true },
    cravingTags: { salty: 0.8, umami: 0.7, comfort: 0.6 },
    emotionTags: { energized: 0.7, comfort: 0.5 },
    qualityScore: 85,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
  },
  {
    title: "Lemon Herb Grilled Chicken",
    description: "Tender chicken breast marinated in lemon, garlic, and fresh herbs with roasted vegetables",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Mediterranean",
    ingredients: [
      { name: "chicken breast", amount: 180, unit: "g" },
      { name: "lemon juice", amount: 2, unit: "tbsp" },
      { name: "garlic", amount: 2, unit: "cloves", notes: "minced" },
      { name: "olive oil", amount: 1, unit: "tbsp" },
      { name: "fresh rosemary", amount: 1, unit: "sprig" },
      { name: "zucchini", amount: 150, unit: "g", notes: "sliced" },
      { name: "bell peppers", amount: 100, unit: "g", notes: "sliced" },
    ],
    steps: [
      "Marinate chicken in lemon juice, garlic, olive oil, and rosemary for 15 minutes.",
      "Preheat grill or grill pan to medium-high heat.",
      "Grill chicken for 6-7 minutes per side until internal temp reaches 165°F.",
      "Grill vegetables alongside chicken for 4-5 minutes.",
      "Let chicken rest 5 minutes before slicing.",
    ],
    macros: { calories: 320, protein: 42, carbs: 12, fat: 12, fiber: 3 },
    allergenFlags: {},
    dietFlags: { glp1: true, diabetes: true, cardiac: true, highProtein: true, lowCarb: true },
    cravingTags: { fresh: 0.9, umami: 0.6, salty: 0.4 },
    emotionTags: { energized: 0.8, celebration: 0.3 },
    qualityScore: 90,
    servings: 2,
    prepMinutes: 20,
    cookMinutes: 15,
  },
  {
    title: "Creamy Garlic Shrimp with Zoodles",
    description: "Succulent shrimp in a light garlic cream sauce over spiralized zucchini noodles",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Italian",
    ingredients: [
      { name: "large shrimp", amount: 200, unit: "g", notes: "peeled and deveined" },
      { name: "zucchini", amount: 300, unit: "g", notes: "spiralized" },
      { name: "garlic", amount: 4, unit: "cloves", notes: "minced" },
      { name: "light cream cheese", amount: 2, unit: "tbsp" },
      { name: "chicken broth", amount: 60, unit: "ml" },
      { name: "parmesan", amount: 20, unit: "g", notes: "grated" },
      { name: "olive oil", amount: 1, unit: "tbsp" },
    ],
    steps: [
      "Heat olive oil in a large skillet over medium-high heat.",
      "Sauté shrimp for 2-3 minutes per side until pink, remove and set aside.",
      "Add garlic to the pan and sauté for 30 seconds.",
      "Stir in cream cheese and broth until smooth sauce forms.",
      "Add zucchini noodles and toss for 2 minutes until slightly softened.",
      "Return shrimp to pan, sprinkle with parmesan, and serve immediately.",
    ],
    macros: { calories: 340, protein: 35, carbs: 14, fat: 16, fiber: 4 },
    allergenFlags: { shellfish: true, dairy: true },
    dietFlags: { glp1: true, lowCarb: true, highProtein: true },
    cravingTags: { creamy: 0.9, umami: 0.8, comfort: 0.7 },
    emotionTags: { celebration: 0.6, comfort: 0.7 },
    qualityScore: 88,
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 10,
  },
  {
    title: "Asian Beef Lettuce Wraps",
    description: "Savory ground beef with Asian aromatics wrapped in crisp butter lettuce",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Asian",
    ingredients: [
      { name: "lean ground beef", amount: 200, unit: "g" },
      { name: "butter lettuce", amount: 8, unit: "leaves" },
      { name: "water chestnuts", amount: 60, unit: "g", notes: "diced" },
      { name: "soy sauce", amount: 2, unit: "tbsp", notes: "low sodium" },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "ginger", amount: 1, unit: "tsp", notes: "minced" },
      { name: "green onions", amount: 2, unit: "stalks", notes: "sliced" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat, breaking into small pieces.",
      "Add ginger and cook for 1 minute until fragrant.",
      "Stir in water chestnuts, soy sauce, and sesame oil.",
      "Cook for 2-3 more minutes until heated through.",
      "Spoon mixture into lettuce cups and garnish with green onions.",
    ],
    macros: { calories: 280, protein: 28, carbs: 10, fat: 14, fiber: 2 },
    allergenFlags: { soy: true },
    dietFlags: { glp1: true, diabetes: true, lowCarb: true, highProtein: true },
    cravingTags: { umami: 0.9, salty: 0.7, crunchy: 0.6 },
    emotionTags: { energized: 0.6 },
    qualityScore: 82,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
  },
  {
    title: "Mediterranean Salmon Bowl",
    description: "Omega-rich salmon over quinoa with cucumber, tomatoes, and tzatziki",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Mediterranean",
    ingredients: [
      { name: "salmon fillet", amount: 180, unit: "g" },
      { name: "quinoa", amount: 100, unit: "g", notes: "cooked" },
      { name: "cucumber", amount: 80, unit: "g", notes: "diced" },
      { name: "cherry tomatoes", amount: 80, unit: "g", notes: "halved" },
      { name: "red onion", amount: 30, unit: "g", notes: "thinly sliced" },
      { name: "tzatziki sauce", amount: 3, unit: "tbsp" },
      { name: "olive oil", amount: 1, unit: "tsp" },
    ],
    steps: [
      "Season salmon with salt and pepper.",
      "Heat olive oil in a skillet over medium-high heat.",
      "Cook salmon skin-side down for 4 minutes, flip and cook 3 more minutes.",
      "Layer quinoa in bowl, top with cucumber, tomatoes, and onion.",
      "Place salmon on top and drizzle with tzatziki.",
    ],
    macros: { calories: 450, protein: 38, carbs: 32, fat: 18, fiber: 5 },
    allergenFlags: { fish: true, dairy: true },
    dietFlags: { cardiac: true, antiInflammatory: true, highProtein: true },
    cravingTags: { fresh: 0.9, umami: 0.6 },
    emotionTags: { energized: 0.8, celebration: 0.4 },
    qualityScore: 92,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
  },
  {
    title: "Comfort Mac and Cheese (Lightened)",
    description: "Creamy cauliflower-based mac and cheese with reduced carbs and boosted protein",
    studio: "craving",
    mealType: "dinner",
    cuisine: "American",
    ingredients: [
      { name: "elbow pasta", amount: 80, unit: "g", notes: "chickpea or protein pasta" },
      { name: "cauliflower", amount: 200, unit: "g", notes: "steamed" },
      { name: "sharp cheddar", amount: 60, unit: "g", notes: "shredded" },
      { name: "milk", amount: 60, unit: "ml", notes: "low-fat" },
      { name: "garlic powder", amount: 0.5, unit: "tsp" },
      { name: "mustard powder", amount: 0.25, unit: "tsp" },
    ],
    steps: [
      "Cook pasta according to package directions, drain and set aside.",
      "Blend steamed cauliflower with milk until smooth.",
      "In a saucepan, heat cauliflower puree over medium heat.",
      "Stir in cheese, garlic powder, and mustard powder until melted.",
      "Toss pasta with cheese sauce and serve immediately.",
    ],
    macros: { calories: 380, protein: 22, carbs: 38, fat: 16, fiber: 6 },
    allergenFlags: { dairy: true, gluten: true },
    dietFlags: { comfort: true },
    cravingTags: { comfort: 1.0, creamy: 0.9, salty: 0.5 },
    emotionTags: { comfort: 0.9, tired: 0.6 },
    qualityScore: 78,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
  },
  {
    title: "Spicy Korean Beef Bowl",
    description: "Gochujang-glazed beef over rice with pickled vegetables and a fried egg",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Korean",
    ingredients: [
      { name: "sirloin steak", amount: 180, unit: "g", notes: "thinly sliced" },
      { name: "brown rice", amount: 120, unit: "g", notes: "cooked" },
      { name: "gochujang", amount: 2, unit: "tbsp" },
      { name: "soy sauce", amount: 1, unit: "tbsp" },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "egg", amount: 1, unit: "large" },
      { name: "kimchi", amount: 60, unit: "g" },
    ],
    steps: [
      "Mix gochujang, soy sauce, and sesame oil in a bowl.",
      "Marinate beef slices for 10 minutes.",
      "Stir-fry beef over high heat for 2-3 minutes until caramelized.",
      "Fry egg sunny-side up in the same pan.",
      "Build bowl: rice base, spicy beef, kimchi, and top with fried egg.",
    ],
    macros: { calories: 480, protein: 36, carbs: 40, fat: 20, fiber: 3 },
    allergenFlags: { soy: true, egg: true },
    dietFlags: { highProtein: true },
    cravingTags: { spicy: 0.9, umami: 0.9, salty: 0.7, comfort: 0.6 },
    emotionTags: { energized: 0.7, comfort: 0.5 },
    qualityScore: 86,
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 10,
  },
  {
    title: "Greek Chicken Souvlaki Plate",
    description: "Grilled chicken skewers with tzatziki, Greek salad, and warm pita",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Greek",
    ingredients: [
      { name: "chicken thighs", amount: 200, unit: "g", notes: "boneless, cubed" },
      { name: "lemon juice", amount: 2, unit: "tbsp" },
      { name: "oregano", amount: 1, unit: "tsp" },
      { name: "cucumber", amount: 80, unit: "g", notes: "diced" },
      { name: "tomatoes", amount: 80, unit: "g", notes: "diced" },
      { name: "feta cheese", amount: 30, unit: "g", notes: "crumbled" },
      { name: "tzatziki", amount: 3, unit: "tbsp" },
    ],
    steps: [
      "Marinate chicken cubes in lemon juice, oregano, olive oil for 20 minutes.",
      "Thread chicken onto skewers.",
      "Grill skewers for 4-5 minutes per side until cooked through.",
      "Toss cucumber, tomatoes, and feta for Greek salad.",
      "Serve skewers with salad and tzatziki on the side.",
    ],
    macros: { calories: 380, protein: 36, carbs: 12, fat: 22, fiber: 2 },
    allergenFlags: { dairy: true },
    dietFlags: { glp1: true, diabetes: true, lowCarb: true, highProtein: true },
    cravingTags: { fresh: 0.8, umami: 0.7, salty: 0.5 },
    emotionTags: { celebration: 0.6, energized: 0.6 },
    qualityScore: 88,
    servings: 2,
    prepMinutes: 25,
    cookMinutes: 10,
  },
  {
    title: "Loaded Sweet Potato",
    description: "Baked sweet potato topped with black beans, Greek yogurt, and fresh salsa",
    studio: "craving",
    mealType: "dinner",
    cuisine: "American",
    ingredients: [
      { name: "sweet potato", amount: 250, unit: "g", notes: "medium, whole" },
      { name: "black beans", amount: 80, unit: "g", notes: "drained" },
      { name: "Greek yogurt", amount: 60, unit: "g", notes: "plain, non-fat" },
      { name: "salsa", amount: 60, unit: "g" },
      { name: "cheddar cheese", amount: 20, unit: "g", notes: "shredded" },
      { name: "green onions", amount: 2, unit: "stalks", notes: "sliced" },
    ],
    steps: [
      "Pierce sweet potato with a fork and microwave 8-10 minutes until soft.",
      "Heat black beans in a small saucepan or microwave.",
      "Cut sweet potato open and fluff the inside.",
      "Top with black beans, Greek yogurt, salsa, and cheese.",
      "Garnish with green onions and serve.",
    ],
    macros: { calories: 340, protein: 18, carbs: 52, fat: 6, fiber: 10 },
    allergenFlags: { dairy: true },
    dietFlags: { vegetarian: true, highFiber: true },
    cravingTags: { comfort: 0.8, salty: 0.5, creamy: 0.4 },
    emotionTags: { comfort: 0.7, tired: 0.5 },
    qualityScore: 80,
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 10,
  },
  {
    title: "Thai Basil Chicken Stir-Fry",
    description: "Aromatic ground chicken with Thai basil, chilies, and garlic over jasmine rice",
    studio: "craving",
    mealType: "dinner",
    cuisine: "Thai",
    ingredients: [
      { name: "ground chicken", amount: 200, unit: "g" },
      { name: "Thai basil", amount: 30, unit: "g", notes: "fresh leaves" },
      { name: "garlic", amount: 4, unit: "cloves", notes: "minced" },
      { name: "Thai chilies", amount: 2, unit: "small", notes: "sliced" },
      { name: "fish sauce", amount: 2, unit: "tbsp" },
      { name: "jasmine rice", amount: 120, unit: "g", notes: "cooked" },
      { name: "vegetable oil", amount: 1, unit: "tbsp" },
    ],
    steps: [
      "Heat oil in a wok or large skillet over high heat.",
      "Add garlic and chilies, stir-fry 30 seconds.",
      "Add ground chicken and break apart, cook 4-5 minutes.",
      "Stir in fish sauce and oyster sauce.",
      "Remove from heat and fold in fresh basil until wilted.",
      "Serve over jasmine rice.",
    ],
    macros: { calories: 420, protein: 32, carbs: 38, fat: 14, fiber: 1 },
    allergenFlags: { fish: true },
    dietFlags: { highProtein: true },
    cravingTags: { spicy: 0.8, umami: 0.9, fresh: 0.6 },
    emotionTags: { energized: 0.8 },
    qualityScore: 85,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
  },
];

const DESSERT_MEALS: SeedMeal[] = [
  {
    title: "Protein Chocolate Mousse",
    description: "Rich, velvety chocolate mousse made with Greek yogurt and protein powder",
    studio: "dessert",
    mealType: "dessert",
    cuisine: "French",
    ingredients: [
      { name: "Greek yogurt", amount: 150, unit: "g", notes: "plain, non-fat" },
      { name: "chocolate protein powder", amount: 30, unit: "g" },
      { name: "cocoa powder", amount: 1, unit: "tbsp" },
      { name: "stevia", amount: 1, unit: "packet" },
      { name: "vanilla extract", amount: 0.5, unit: "tsp" },
    ],
    steps: [
      "Combine Greek yogurt and protein powder in a bowl.",
      "Add cocoa powder, stevia, and vanilla extract.",
      "Whisk until smooth and creamy.",
      "Refrigerate for 30 minutes to set.",
      "Serve chilled with a sprinkle of cocoa.",
    ],
    macros: { calories: 180, protein: 28, carbs: 12, fat: 3, fiber: 2 },
    allergenFlags: { dairy: true },
    dietFlags: { glp1: true, diabetes: true, highProtein: true, lowCarb: true },
    cravingTags: { sweet: 0.9, creamy: 0.8, comfort: 0.7 },
    emotionTags: { comfort: 0.8, celebration: 0.5 },
    qualityScore: 88,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
  },
  {
    title: "Berry Chia Parfait",
    description: "Layered chia pudding with mixed berries and a touch of honey",
    studio: "dessert",
    mealType: "dessert",
    cuisine: "American",
    ingredients: [
      { name: "chia seeds", amount: 3, unit: "tbsp" },
      { name: "almond milk", amount: 200, unit: "ml", notes: "unsweetened" },
      { name: "mixed berries", amount: 100, unit: "g" },
      { name: "honey", amount: 1, unit: "tsp" },
      { name: "vanilla extract", amount: 0.5, unit: "tsp" },
    ],
    steps: [
      "Mix chia seeds with almond milk and vanilla in a jar.",
      "Refrigerate overnight or at least 4 hours until thick.",
      "Layer chia pudding with fresh berries in a glass.",
      "Drizzle with honey and serve.",
    ],
    macros: { calories: 160, protein: 5, carbs: 22, fat: 7, fiber: 9 },
    allergenFlags: {},
    dietFlags: { glp1: true, diabetes: true, vegan: true, highFiber: true },
    cravingTags: { sweet: 0.7, fresh: 0.8 },
    emotionTags: { energized: 0.6 },
    qualityScore: 85,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
  },
  {
    title: "Baked Cinnamon Apple Slices",
    description: "Warm spiced apple slices baked until tender with a hint of maple",
    studio: "dessert",
    mealType: "dessert",
    cuisine: "American",
    ingredients: [
      { name: "apple", amount: 200, unit: "g", notes: "Honeycrisp, sliced" },
      { name: "cinnamon", amount: 1, unit: "tsp" },
      { name: "maple syrup", amount: 1, unit: "tbsp" },
      { name: "butter", amount: 1, unit: "tsp" },
      { name: "walnuts", amount: 15, unit: "g", notes: "chopped" },
    ],
    steps: [
      "Preheat oven to 375°F (190°C).",
      "Toss apple slices with cinnamon and maple syrup.",
      "Arrange in a baking dish and dot with butter.",
      "Bake for 20-25 minutes until tender.",
      "Top with chopped walnuts and serve warm.",
    ],
    macros: { calories: 140, protein: 2, carbs: 24, fat: 5, fiber: 4 },
    allergenFlags: { treeNut: true, dairy: true },
    dietFlags: { glp1: true },
    cravingTags: { sweet: 0.8, comfort: 0.9 },
    emotionTags: { comfort: 0.9, tired: 0.4 },
    qualityScore: 82,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 25,
  },
  {
    title: "Frozen Banana Nice Cream",
    description: "Creamy one-ingredient ice cream made from frozen bananas",
    studio: "dessert",
    mealType: "dessert",
    cuisine: "American",
    ingredients: [
      { name: "frozen banana", amount: 200, unit: "g", notes: "sliced and frozen" },
      { name: "cocoa powder", amount: 1, unit: "tbsp", notes: "optional" },
      { name: "peanut butter", amount: 1, unit: "tbsp", notes: "optional" },
    ],
    steps: [
      "Add frozen banana slices to a food processor.",
      "Blend until smooth and creamy, scraping sides as needed.",
      "Add cocoa powder or peanut butter for flavor variations.",
      "Serve immediately for soft-serve texture or freeze for firmer ice cream.",
    ],
    macros: { calories: 120, protein: 2, carbs: 28, fat: 1, fiber: 3 },
    allergenFlags: { peanut: true },
    dietFlags: { vegan: true },
    cravingTags: { sweet: 0.9, creamy: 0.8, comfort: 0.6 },
    emotionTags: { celebration: 0.5, comfort: 0.6 },
    qualityScore: 80,
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
  },
  {
    title: "Greek Yogurt Bark",
    description: "Frozen yogurt bark studded with berries and dark chocolate chips",
    studio: "dessert",
    mealType: "dessert",
    cuisine: "American",
    ingredients: [
      { name: "Greek yogurt", amount: 200, unit: "g", notes: "vanilla or plain" },
      { name: "mixed berries", amount: 80, unit: "g" },
      { name: "dark chocolate chips", amount: 20, unit: "g" },
      { name: "honey", amount: 1, unit: "tbsp" },
    ],
    steps: [
      "Line a baking sheet with parchment paper.",
      "Spread Greek yogurt in an even layer about 1/4 inch thick.",
      "Scatter berries and chocolate chips on top.",
      "Drizzle with honey.",
      "Freeze for 2 hours until solid, break into pieces.",
    ],
    macros: { calories: 140, protein: 10, carbs: 18, fat: 4, fiber: 2 },
    allergenFlags: { dairy: true },
    dietFlags: { glp1: true, highProtein: true },
    cravingTags: { sweet: 0.8, crunchy: 0.5, fresh: 0.4 },
    emotionTags: { celebration: 0.6 },
    qualityScore: 84,
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
  },
];

const FRIDGE_MEALS: SeedMeal[] = [
  {
    title: "Protein + Veggie Stir-Fry Base",
    description: "Flexible stir-fry template: any protein with available vegetables",
    studio: "fridge",
    mealType: "dinner",
    cuisine: "Asian",
    ingredients: [
      { name: "protein of choice", amount: 200, unit: "g", notes: "chicken, beef, tofu, or shrimp" },
      { name: "mixed vegetables", amount: 300, unit: "g", notes: "whatever you have" },
      { name: "soy sauce", amount: 2, unit: "tbsp" },
      { name: "garlic", amount: 2, unit: "cloves", notes: "minced" },
      { name: "ginger", amount: 1, unit: "tsp", notes: "minced" },
      { name: "vegetable oil", amount: 1, unit: "tbsp" },
    ],
    steps: [
      "Cut protein into bite-sized pieces.",
      "Heat oil in wok or large skillet over high heat.",
      "Stir-fry protein until cooked, about 4-5 minutes. Set aside.",
      "Add vegetables starting with hardest (carrots, broccoli) first.",
      "Add garlic and ginger, stir-fry 30 seconds.",
      "Return protein to pan, add soy sauce, toss to combine.",
    ],
    macros: { calories: 320, protein: 32, carbs: 18, fat: 14, fiber: 5 },
    allergenFlags: { soy: true },
    dietFlags: { glp1: true, highProtein: true },
    cravingTags: { umami: 0.8, salty: 0.6 },
    emotionTags: { energized: 0.6 },
    qualityScore: 85,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
  },
  {
    title: "Egg Scramble with Whatever's Available",
    description: "Quick eggs with any vegetables and cheese you have on hand",
    studio: "fridge",
    mealType: "breakfast",
    cuisine: "American",
    ingredients: [
      { name: "eggs", amount: 3, unit: "large" },
      { name: "vegetables", amount: 100, unit: "g", notes: "bell peppers, onions, spinach, etc." },
      { name: "cheese", amount: 30, unit: "g", notes: "any type, shredded" },
      { name: "butter", amount: 1, unit: "tsp" },
      { name: "salt and pepper", amount: 1, unit: "pinch" },
    ],
    steps: [
      "Beat eggs in a bowl with salt and pepper.",
      "Sauté vegetables in butter until softened.",
      "Pour eggs over vegetables and scramble gently.",
      "When eggs are almost set, sprinkle with cheese.",
      "Cover briefly to melt cheese, then serve.",
    ],
    macros: { calories: 280, protein: 20, carbs: 6, fat: 20, fiber: 1 },
    allergenFlags: { egg: true, dairy: true },
    dietFlags: { keto: true, lowCarb: true, highProtein: true },
    cravingTags: { comfort: 0.8, salty: 0.5, creamy: 0.4 },
    emotionTags: { comfort: 0.7, tired: 0.5 },
    qualityScore: 82,
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 5,
  },
  {
    title: "Grain Bowl Template",
    description: "Build-your-own bowl with grains, protein, veggies, and sauce",
    studio: "fridge",
    mealType: "lunch",
    cuisine: "Mediterranean",
    ingredients: [
      { name: "grain base", amount: 150, unit: "g", notes: "rice, quinoa, farro, etc." },
      { name: "protein", amount: 150, unit: "g", notes: "chicken, chickpeas, tofu, etc." },
      { name: "roasted vegetables", amount: 150, unit: "g", notes: "any available" },
      { name: "dressing", amount: 2, unit: "tbsp", notes: "tahini, vinaigrette, etc." },
      { name: "greens", amount: 50, unit: "g", notes: "optional, for base" },
    ],
    steps: [
      "Prepare grain according to package directions (or use leftover).",
      "Cook or heat protein of choice.",
      "Roast or sauté vegetables until tender.",
      "Layer greens in bowl, add grain, protein, and vegetables.",
      "Drizzle with dressing and serve.",
    ],
    macros: { calories: 420, protein: 28, carbs: 45, fat: 14, fiber: 6 },
    allergenFlags: {},
    dietFlags: { highProtein: true },
    cravingTags: { comfort: 0.6, fresh: 0.5, umami: 0.5 },
    emotionTags: { energized: 0.6 },
    qualityScore: 84,
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 20,
  },
  {
    title: "Quick Soup from Leftovers",
    description: "Transform leftover proteins and vegetables into a warming soup",
    studio: "fridge",
    mealType: "dinner",
    cuisine: "American",
    ingredients: [
      { name: "chicken broth", amount: 500, unit: "ml" },
      { name: "leftover protein", amount: 150, unit: "g", notes: "shredded or cubed" },
      { name: "vegetables", amount: 200, unit: "g", notes: "any available" },
      { name: "garlic", amount: 2, unit: "cloves", notes: "minced" },
      { name: "herbs", amount: 1, unit: "tsp", notes: "thyme, oregano, etc." },
    ],
    steps: [
      "Bring broth to a simmer in a pot.",
      "Add harder vegetables first (carrots, potatoes) and cook 10 minutes.",
      "Add softer vegetables and garlic, cook 5 more minutes.",
      "Add leftover protein and herbs, heat through.",
      "Season to taste and serve.",
    ],
    macros: { calories: 220, protein: 22, carbs: 18, fat: 6, fiber: 4 },
    allergenFlags: {},
    dietFlags: { glp1: true, diabetes: true },
    cravingTags: { comfort: 0.9, umami: 0.7 },
    emotionTags: { comfort: 0.9, tired: 0.7, stress: 0.5 },
    qualityScore: 80,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 20,
  },
  {
    title: "Wrap or Burrito with Pantry Items",
    description: "Quick wrap using whatever proteins, veggies, and sauces you have",
    studio: "fridge",
    mealType: "lunch",
    cuisine: "Mexican",
    ingredients: [
      { name: "large tortilla", amount: 2, unit: "large" },
      { name: "protein", amount: 150, unit: "g", notes: "beans, chicken, ground meat" },
      { name: "vegetables", amount: 100, unit: "g", notes: "lettuce, tomatoes, peppers" },
      { name: "cheese", amount: 40, unit: "g", notes: "shredded" },
      { name: "salsa or sauce", amount: 3, unit: "tbsp" },
    ],
    steps: [
      "Warm tortillas in microwave or dry skillet.",
      "Heat protein if needed.",
      "Layer protein, vegetables, cheese, and sauce in center of tortilla.",
      "Fold sides in, then roll tightly from bottom.",
      "Optional: grill seam-side down for crispy exterior.",
    ],
    macros: { calories: 380, protein: 24, carbs: 35, fat: 16, fiber: 5 },
    allergenFlags: { gluten: true, dairy: true },
    dietFlags: { highProtein: true },
    cravingTags: { comfort: 0.7, salty: 0.6 },
    emotionTags: { comfort: 0.6 },
    qualityScore: 78,
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 5,
  },
];

async function seedMealLibrary() {
  console.log("🌱 Starting meal library seed...");
  
  const allMeals = [...CRAVING_MEALS, ...DESSERT_MEALS, ...FRIDGE_MEALS];
  let inserted = 0;
  
  for (const meal of allMeals) {
    try {
      const searchText = [
        meal.title,
        meal.description,
        meal.cuisine || "",
        Object.keys(meal.cravingTags).filter(k => meal.cravingTags[k] > 0.5).join(" "),
        meal.ingredients.map(i => i.name).join(" "),
      ].join(" ").toLowerCase();
      
      await db.insert(mealLibraryItems).values({
        title: meal.title,
        description: meal.description,
        studio: meal.studio,
        mealType: meal.mealType,
        cuisine: meal.cuisine,
        ingredientsJson: meal.ingredients,
        stepsJson: meal.steps,
        macrosJson: meal.macros,
        allergenFlagsJson: meal.allergenFlags,
        dietFlagsJson: meal.dietFlags,
        cravingTagsJson: meal.cravingTags,
        emotionTagsJson: meal.emotionTags,
        searchText,
        qualityScore: meal.qualityScore,
        servings: meal.servings,
        prepMinutes: meal.prepMinutes,
        cookMinutes: meal.cookMinutes,
      });
      inserted++;
      console.log(`  ✓ ${meal.title}`);
    } catch (error) {
      console.error(`  ✗ Failed to insert ${meal.title}:`, error);
    }
  }
  
  console.log(`\n✅ Seed complete: ${inserted}/${allMeals.length} meals inserted`);
  console.log(`   - Craving: ${CRAVING_MEALS.length}`);
  console.log(`   - Dessert: ${DESSERT_MEALS.length}`);
  console.log(`   - Fridge: ${FRIDGE_MEALS.length}`);
}

seedMealLibrary()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
